name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
        - amd64
        - arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binary
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            CC=aarch64-linux-gnu-gcc make build
          else
            make build
          fi
        env:
          GOARCH: ${{ matrix.arch }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: redfishcli-${{ matrix.arch }}
          path: redfishcli-${{ matrix.arch }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download X86_64 binary
        uses: actions/download-artifact@v4
        with:
          name: redfishcli-linux-amd64
          path: ./release/

      - name: Download ARM64 binary
        uses: actions/download-artifact@v4
        with:
          name: redfishcli-linux-arm64
          path: ./release/

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes

      - name: Upload Release Asset for X86_64
        uses: actions/upload-artifact@v4
        with:
          name: redfishcli-amd64
          path: ./release/redfishcli-amd64-${{ github.ref }}.tar.gz

      - name: Upload Release Asset for ARM64
        uses: actions/upload-artifact@v4
        with:
          name: redfishcli-arm64
          path: ./release/redfishcli-arm64-${{ github.ref }}.tar.gz
